name: Run Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SECRET_KEY: random-secret-key-for-ci
  DEBUG: True
  ALLOWED_HOSTS: 'testserver'
  TIME_ZONE: 'Asia/Bangkok'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations and Tests
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test
