name: Run Flake8 & Flake8 docstrings

on:
  push:
    branches: [ "main", "iteration4" ]
  pull_request:
    branches: [ "main", "iteration4" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create Flake8 config
      run: |
        echo "[flake8]" > .flake8
        echo "exclude = __init__.py,*/migrations/*" >> .flake8
        echo "ignore = D100,D101,D104" >> .flake8
        echo "per-file-ignores =" >> .flake8
        echo "    models.py:D100,D101,D102,D105,D106" >> .flake8
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --exclude=test_*.py #sth # count how many problem, --exit-zero is successful program termination
